# 게임설정값
#BOT_TOKEN을 입력해 둔 채로 commit하지 말것!!!!

INITIAL_COIN = 15
ROUND_COIN_FIRST_HALF = 5
ROUND_COIN_SECOND_HALF = 10

MASTER_ROUND_ON_FIRST_ROUND = 0 # 0 또는 1
MASTER_ROUND_ON_LAST_ROUND = 1 # 0 또는 1

BOT_TOKEN = ""
